# Generated by Django 5.1.2 on 2024-11-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='live_demo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
